// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Providers } from "@/redux/provider";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
    
//     <html lang="en">
     
//       <body className={inter.className}>
//       <Providers>
//         {children}
//         </Providers>
//       </body>
      
//     </html>
    
//   );
// }


import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/redux/provider";
import Appbar from "@/components/Appbar";
import ClientLayout from "@/components/ClientLayout";
const montserrat = Montserrat({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "D-Kart Website - Dhruv Patel",
  description: "Buy the best product at cheaper rates",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
